server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db.wjvqixjqnfyxdrotieli.supabase.co:5432/postgres?user=postgres&password=zkiXvDVy1aOrGiCt}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:zkiXvDVy1aOrGiCt}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:MiClaveSecretaSuperSeguraParaJWT2025HospitalMedicamentos12345}
jwt.expiration=${JWT_EXPIRATION:86400000}
