server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${DATABASE_USERNAME:postgres.moppiopsliefhdivrtqy}
spring.datasource.password=${DATABASE_PASSWORD:FM1sPTonprXoXj3V}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:MiClaveSecretaSuperSeguraParaJWT2025HospitalMedicamentos12345}
jwt.expiration=${JWT_EXPIRATION:86400000}
